# Generated by Django 2.2 on 2019-04-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total_population', models.CharField(max_length=150)),
                ('countries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gdp_per_captia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gini', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unemployment', models.DecimalField(decimal_places=2, max_digits=4)),
                ('poverty_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('gov_type', models.CharField(max_length=150)),
                ('total_population', models.IntegerField()),
            ],
        ),
    ]
