# Generated by Django 2.2 on 2019-04-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_auto_20190401_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financial',
            new_name='Economic',
        ),
    ]
