# Generated by Django 2.2 on 2019-04-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0004_auto_20190401_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Nations',
        ),
    ]
